version: '3.8'
services:
  flask:
    build:
      context: .
    container_name: flask-container
    restart: always
    ports:
      - "13680:8000"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./main:/usr/src/app
